In [1]:
#uploading library
import numpy as np

In [8]:
#basic calculations
print(np.add(12,34))
print(np.subtract(365,34))
print(np.multiply(2,68))
print(np.sqrt(123))
print(np.cos(np.pi))

46
331
136
11.090536506409418
-1.0


In [21]:
#creating numpy array using lists
arr = np.array([23,54,34])
print(arr)

[23 54 34]


In [11]:
#creating matrices using lists
matx = np.array([[1,2,3],[34,56,75],[12,45,32]])
print(matx)

[[ 1  2  3]
 [34 56 75]
 [12 45 32]]


In [16]:
#other ways to create numpy arrays
aur = np.arange(0,10)
print(aur)
arr2 = np.arange(2,16,5)
print(arr2)
arr3 = np.linspace(0,35,5)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[ 2  7 12]
[ 0.    8.75 17.5  26.25 35.  ]


In [18]:
#other ways to create matrices using numpy
matx1 = np.zeros([7,4])
print(matx1)
matx2 = np.ones((3,5))
print(matx2)
matx3 = np.eye(4)
print(matx3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
# if size is same we can perform array +,-,*,/
ar1 = np.arange(1,7)
ar2 = np.arange(3,9)
print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)

[ 4  6  8 10 12 14]
[-2 -2 -2 -2 -2 -2]
[ 3  8 15 24 35 48]


In [25]:
#matrix multiplication
mult = np.matmul(matx,arr)
print(mult)

#solving a linear matrix equation
print(np.linalg.solve(matx,mult))

[ 233 6356 3794]
[23. 54. 34.]


In [27]:
# generating samples of random variables
rmat = np.random.rand(4,4) #uniform random variable
print(rmat)
rmat1 = np.random.randn(5,3) #standard random variable
print(rmat1)


[[0.47110959 0.46046734 0.97049715 0.60912994]
 [0.38155871 0.22144951 0.84303804 0.94846801]
 [0.23863049 0.57947453 0.58420017 0.62466356]
 [0.59559525 0.13047666 0.4779596  0.23949584]]
[[ 2.48878889 -1.36139261  1.50242006]
 [ 0.37336214  1.02532592 -0.62505562]
 [ 0.90357387 -0.51277492 -0.55558107]
 [ 0.22904895  0.42694013  0.12042023]
 [ 0.55042989 -1.44942594  1.25989744]]


In [29]:
#statistics using numpy
print(np.mean(matx))
print(np.std(matx))
print(np.min(matx))
print(np.max(matx))

28.88888888888889
24.973071917320354
1
75


In [30]:
# accessing variables in numpy array
new_arr = np.random.randn(20)
print(new_arr)
print(new_arr[8])
print(new_arr[2:10])

[-8.53965193e-01  5.78972194e-01 -3.49552510e-01  7.66360383e-01
 -2.21052538e-01 -7.76525462e-01 -2.91064837e-01  5.99559684e-01
 -3.35459373e-01 -1.20219501e+00 -2.73108899e+00 -1.26172799e+00
  3.56547485e-01 -2.31947648e-01 -1.26149755e-01 -4.14742259e-01
  9.51316890e-01 -5.68075195e-01 -1.34588476e-03 -1.05685823e+00]
-0.3354593727721057
[-0.34955251  0.76636038 -0.22105254 -0.77652546 -0.29106484  0.59955968
 -0.33545937 -1.20219501]


In [34]:
#accessing matrices
print(matx)
print(matx[1][2])
print(matx[0:2,0:3])

[[ 1  2  3]
 [34 56 75]
 [12 45 32]]
75
[[ 1  2  3]
 [34 56 75]]


In [37]:
#reassigning values
new_arr[2:4] = 3
print(new_arr)
new_arr[2:4] = [2,3]
print(new_arr)

[-8.53965193e-01  5.78972194e-01  3.00000000e+00  3.00000000e+00
 -2.21052538e-01 -7.76525462e-01 -2.91064837e-01  5.99559684e-01
 -3.35459373e-01 -1.20219501e+00 -2.73108899e+00 -1.26172799e+00
  3.56547485e-01 -2.31947648e-01 -1.26149755e-01 -4.14742259e-01
  9.51316890e-01 -5.68075195e-01 -1.34588476e-03 -1.05685823e+00]
[-8.53965193e-01  5.78972194e-01  2.00000000e+00  3.00000000e+00
 -2.21052538e-01 -7.76525462e-01 -2.91064837e-01  5.99559684e-01
 -3.35459373e-01 -1.20219501e+00 -2.73108899e+00 -1.26172799e+00
  3.56547485e-01 -2.31947648e-01 -1.26149755e-01 -4.14742259e-01
  9.51316890e-01 -5.68075195e-01 -1.34588476e-03 -1.05685823e+00]


In [39]:
matx[1:3,1:3] = 0
print(matx)

[[ 1  2  3]
 [34  0  0]
 [12  0  0]]


In [41]:
#we can also access using logic
print(new_arr>0)
print(new_arr[new_arr>0])
print(matx>0)
print(new_arr[new_arr>0])

[False  True  True  True False False False  True False False False False
  True False False False  True False False False]
[0.57897219 2.         3.         0.59955968 0.35654748 0.95131689]
